# Generated by Django 3.0.6 on 2020-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0004_auto_20200615_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='no_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='status',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
