# Generated by Django 3.0.6 on 2020-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0006_auto_20200615_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='status',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
