# Generated by Django 3.0.6 on 2020-07-20 06:44

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0007_auto_20200622_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobile',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(),
        ),
    ]
