# Generated by Django 3.0.6 on 2020-07-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0009_auto_20200720_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='mobile',
            new_name='mobileNO',
        ),
    ]
