# Generated by Django 3.0.6 on 2020-11-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0018_customers_hairdresser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='hairdresser',
            field=models.CharField(max_length=100),
        ),
    ]
