# Generated by Django 3.0.6 on 2020-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0020_auto_20201123_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='barber',
            field=models.CharField(max_length=100),
        ),
    ]
