# Generated by Django 3.0.6 on 2020-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0022_auto_20201123_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='barber',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
