# Generated by Django 3.0.6 on 2020-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0027_auto_20201124_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='barber',
            field=models.CharField(max_length=100),
        ),
    ]
