# Generated by Django 3.0.6 on 2020-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0005_auto_20200615_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='status',
            field=models.CharField(default='Available', max_length=40),
        ),
    ]
