# Generated by Django 3.0.6 on 2020-07-20 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0008_auto_20200720_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
