# Generated by Django 3.0.6 on 2020-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0010_auto_20200720_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='mobileNO',
        ),
        migrations.AddField(
            model_name='customers',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
