# Generated by Django 3.0.6 on 2020-07-20 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0011_auto_20200720_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customers',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
