# Generated by Django 3.0.6 on 2020-11-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0017_barbers_shopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='hairdresser',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
