# Generated by Django 3.0.6 on 2020-11-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0019_auto_20201123_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='barber',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
