# Generated by Django 3.0.6 on 2020-11-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0024_auto_20201124_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='hairdresser',
            new_name='barber',
        ),
    ]
