# Generated by Django 3.0.6 on 2020-11-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0028_auto_20201124_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='barber',
            new_name='hairdresser',
        ),
    ]
